import Navbar from '@/Component/Navbar'
import './globals.css'
import { Ubuntu } from 'next/font/google'
import Sidebar from '@/Component/Sidebar'

const inter = Ubuntu({ subsets: ['greek'], weight: "400"})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="bg-[#1e1e1e]">
      <Navbar />
        {children}</body>
    </html>
  )
}
